#pragma once

#include "GameInstance.h"

namespace Client
{
	enum LEVEL { LEVEL_STATIC, LEVEL_LOADING, LEVEL_LOGO, LEVEL_MAIN_MENU,LEVEL_STAGE_LOAD, LEVEL_GAMEPLAY,LEVEL_RESULT, LEVEL_EDITOR, LEVEL_END };

	enum class UI_ORDER {
		ORDER_PRIORITY, ORDER_FRONT, ORDER_MIDDLE_FRONT, ORDER_MIDDLE, ORDER_MIDDLE_LAST, ORDER_LAST, _END
	};

	enum Load_Layer { LAYER_TILE, LAYER_PROP, LAYER_INTERACT, LAYER_COLLISION, LAYER_SPONE, LAYER_GIMMIC, LAYER_END };

	enum CHEF_STATE { STATE_NONE, STATE_GRIP_L, STATE_GRIP_R, STATE_HOLD, STATE_DASH, STATE_THROW_HOLD, STATE_INTERACTION, STATE_END };

	enum CHEF_ANIMATION {
		ANIM_BINDPOSE, ANIM_CATCH, ANIM_CHOP, ANIM_DASH, ANIM_DASH_HOLDING, ANIM_DEATH, ANIM_FRY, ANIM_IDLE, ANIM_IDLE_HOLDING,
		ANIM_MIX, ANIM_POUR, ANIM_ROLL, ANIM_STAND, ANIM_THROW, ANIM_WALK, ANIM_WALK_HOLDING, ANIM_WASH, ANIM_END
	};

	enum BELONGING_TYPE {
		BELONGING_NONE, BELONGING_INGREDIENT, BELONGING_PLATE, BELONGING_DIRTY_PLATE, BELONGING_COOKER, BELONGING_END
	};

	enum COOKER_TYPE {
		COOKER_NONE, COOKER_FRYINGPAN, COOKER_POT, COOKER_FRYER_BASKET, COOKER_END
	};

	// 상호작용 가능한 타입
	// 재료중에 접시에 놓는게 불가능한 재료가 있음
	enum REACTION_ENABLE_TYPE {
		REACTION_PLATE = 1, REACTION_CHOP_TABLE, REACTION_FRYINGPAN, REACTION_FRYINGNET, REACTION_BOIL, REACTION_END
	};

	// 상호작용 하는 오브젝트의 타입
	enum INTERACTIVE_OBJECT_TYPE {
		OBJECT_NONE, OBJECT_TABLE, OBJECT_INGREDIENTCRATE, OBJECT_CHOPTABLE, OBJECT_STOVE,
		OBJECT_FRYER, OBJECT_SINK, OBJECT_PLATE_RETURN, OBJECT_PASS, OBJECT_WASTE_BIN, OBJECT_CONVEYOR, OBJECT_DISPENSER, OBJECT_END
	};

	// 상호작용 할 때 사용되는 오브젝트 타입
	enum INTERACTIVE_TOOL_TYPE {
		TOOL_NONE, TOOL_KNIFE, TOOL_CLEAVER, TOOL_HATCHET, TOOL_PLATE, TOOL_END
	};

	// 가이드
	// https://steamcommunity.com/sharedfiles/filedetails/?id=1769729191

	// 재료 타입(종류)
	enum INGREDIENT_TYPE {
		INGREDIENT_NONE, 
		INGREDIENT_TOMATO, INGREDIENT_ONION,INGREDIENT_POTATO, INGREDIENT_DOUGH, INGREDIENT_SEAWEED,
		INGREDIENT_MUSHROOM, INGREDIENT_MEAT, INGREDIENT_LETTUCE, INGREDIENT_RICE, INGREDIENT_FLOUR,
		INGREDIENT_BUN, INGREDIENT_FISH, INGREDIENT_SAUSAGE, INGREDIENT_14, INGREDIENT_EGG,
		INGREDIENT_CHICKEN, INGREDIENT_TORTILLA, INGREDIENT_CHEESE,INGREDIENT_CARROT, INGREDIENT_CHOCOLATE,
		INGREDIENT_HONEY, INGREDIENT_PASTA, INGREDIENT_PRAWN, INGREDIENT_CUCUMBER,
		INGREDIENT_END
	};

	enum COOKING_METHOD_TYPE {
		METHOD_NONE, METHOD_CHOP, METHOD_ROAST, METHOD_BOIL, METHOD_FRYED, METHOD_END
	};

	typedef struct tagRecipe_Desc {
		INGREDIENT_TYPE eIngredientType = { INGREDIENT_END };
		COOKING_METHOD_TYPE eMethod = { METHOD_END };
	}RECIPE_DESC;

	typedef struct tagStage_Score_Info {
		_uint iTotalScore = { 0 };
		_uint iNumPassedOrder = { 0 };
		_uint iOrderScore = { 0 };
		_uint iTipScore = { 0 };

	}STAGE_SCORE_INFO;

	const unsigned int	g_iWinSizeX = 1280;
	const unsigned int	g_iWinSizeY = 720;
}

extern HWND g_hWnd;
extern HINSTANCE g_hInst;

extern _uint g_iStageIdx;

using namespace std;
using namespace Client;
